import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: ["class"],
  content: ["./src/**/*.{js,ts,jsx,tsx,mdx}"],
  theme: {
    extend: {
      colors: {
        paper: {
          0: "var(--paper-0)",
          1: "var(--paper-1)",
          2: "var(--paper-2)",
          3: "var(--paper-3)",
        },
        roast: {
          950: "var(--roast-950)",
          900: "var(--roast-900)",
          800: "var(--roast-800)",
          700: "var(--roast-700)",
          600: "var(--roast-600)",
          500: "var(--roast-500)",
        },
        ink: {
          900: "var(--ink-900)",
          800: "var(--ink-800)",
          700: "var(--ink-700)",
          500: "var(--ink-500)",
          400: "var(--ink-400)",
        },
        coral: {
          600: "var(--coral-600)",
          500: "var(--coral-500)",
          300: "var(--coral-300)",
        },
        brass: { 500: "var(--brass-500)" },
        amber: { 600: "var(--amber-600)" },
        teal: { 500: "var(--teal-500)" },
        green: { 500: "var(--green-500)" },
        red: { 500: "var(--red-500)" },
        bg: "var(--bg)",
        surface: "var(--surface)",
        "surface-raised": "var(--surface-raised)",
        "surface-sunken": "var(--surface-sunken)",
        border: "var(--border)",
        "border-strong": "var(--border-strong)",
        text: "var(--text)",
        "text-body": "var(--text-body)",
        "text-muted": "var(--text-muted)",
        "text-faint": "var(--text-faint)",
        accent: "var(--accent)",
        "accent-active": "var(--accent-active)",
        "on-dark": "var(--on-dark)",
        "on-dark-soft": "var(--on-dark-soft)",
        "on-dark-faint": "var(--on-dark-faint)",
        "on-primary": "var(--on-primary)",
        "status-new": "var(--status-new)",
        "status-new-bg": "var(--status-new-bg)",
        "status-new-ink": "var(--status-new-ink)",
        "status-preparing": "var(--status-preparing)",
        "status-preparing-bg": "var(--status-preparing-bg)",
        "status-preparing-ink": "var(--status-preparing-ink)",
        "status-served": "var(--status-served)",
        "status-served-bg": "var(--status-served-bg)",
        "status-served-ink": "var(--status-served-ink)",
        "status-cancelled": "var(--status-cancelled)",
        "status-cancelled-bg": "var(--status-cancelled-bg)",
        "status-cancelled-ink": "var(--status-cancelled-ink)",
        veg: "var(--veg)",
        nonveg: "var(--nonveg)",
        egg: "var(--egg)",
      },
      fontFamily: {
        display: "var(--font-display)",
        sans: "var(--font-sans)",
        mono: "var(--font-mono)",
      },
      borderRadius: {
        xs: "var(--r-xs)",
        sm: "var(--r-sm)",
        md: "var(--r-md)",
        lg: "var(--r-lg)",
        xl: "var(--r-xl)",
        "2xl": "var(--r-2xl)",
        pill: "var(--r-pill)",
      },
      boxShadow: {
        1: "var(--shadow-1)",
        2: "var(--shadow-2)",
        sheet: "var(--shadow-sheet)",
        toast: "var(--shadow-toast)",
      },
      spacing: {
        "sp-1": "var(--sp-1)",
        "sp-2": "var(--sp-2)",
        "sp-3": "var(--sp-3)",
        "sp-4": "var(--sp-4)",
        "sp-5": "var(--sp-5)",
        "sp-6": "var(--sp-6)",
        "sp-7": "var(--sp-7)",
        "sp-8": "var(--sp-8)",
      },
      transitionDuration: {
        fast: "var(--dur-fast)",
        base: "var(--dur-base)",
        slow: "var(--dur-slow)",
      },
      keyframes: {
        "rt-pulse": {
          "0%, 100%": { opacity: "1" },
          "50%": { opacity: "0.55" },
        },
        "rt-fade": {
          from: { opacity: "0" },
          to: { opacity: "1" },
        },
        "rt-sheet-in": {
          from: { transform: "translateY(14%)", opacity: "0.6" },
          to: { transform: "none", opacity: "1" },
        },
        "rt-toast-in": {
          from: { transform: "translateY(10px)", opacity: "0" },
          to: { transform: "none", opacity: "1" },
        },
        "rt-ring": {
          "0%, 100%": { boxShadow: "0 0 0 3px var(--status-new-bg)" },
          "50%": { boxShadow: "0 0 0 7px var(--status-new-bg)" },
        },
      },
      animation: {
        "rt-pulse": "rt-pulse 1.6s ease-in-out infinite",
        "rt-fade": "rt-fade 200ms var(--ease-out)",
        "rt-sheet-in": "rt-sheet-in 280ms var(--ease-snap)",
        "rt-toast-in": "rt-toast-in 200ms var(--ease-out)",
        "rt-ring": "rt-ring 1.8s ease-in-out infinite",
      },
    },
  },
  plugins: [],
};

export default config;
